compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://npm.pkg.github.com"

npmScopes:
  bricksandbraces:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
  openbricksandbraces:
    npmAlwaysAuth: true
    npmRegistryServer: "https://registry.npmjs.com"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
