name: End-to-end tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    name: "Test stories with cypress"
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install --immutable
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:storybook
          start: yarn start:storybook
          wait-on: http://localhost:6006
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
