name: Publish Package to npm

on:
  release:
    types: [created]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
      - run: yarn config set -H 'npmRegistries["https://registry.npmjs.org"].npmAuthToken' $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn config set -H npmScopes.openbricksandbraces.npmAuthToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn install --immutable
      - run: yarn build:package
      - run: yarn npm publish --tag latest
