name: Publish Package to npm

on:
  release:
    types: [created]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          registry-url: "https://registry.npmjs.com"
      - run: \{ echo "openbricksandbraces"; sleep 1; echo $NPM_PW; \} | yarn npm login
      - run: yarn install --immutable
      - run: yarn build:package
      - run: yarn npm info
      - run: yarn npm whoami
      - run: yarn npm publish --tag latest
